### ISSUE TITLE
flux YAML constructorArgs incorrect formatting for string:number

### ISSUE THREAD

**Issue by Richard-Mathie** [Parsely/streamparse#361]
```
args = [unicode(s) for ['zookeeper:2181', 'something else']]
JavaSpout.spec(name="some-java-spout",
                          full_class_name="com.me.spouts.Spout",
                          args_list=args)
```

gives flux yaml like
```
spouts:
- className: com.me.spouts.Spout
  constructorArgs: [zookeeper:2181, 'something else']
  id: some-java-spout
```

which is invalid yaml due to the `string:number` and storm crys
```
Parsing file: /tmp/tmpkzByyV.yaml
296  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
298  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
298  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
Exception in thread "main" while scanning a plain scalar
 in 'string', line x, column y:
     ... s: [zookeeper:2181, 'something else']
             ^
found unexpected ':'
 in 'string', line x, column y:
     ... [zookeeper:2181, 'something else']
                   ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
```

**Comment by Richard-Mathie** [comment]
for now I just specify
`'zookeeper:2181,zookeeper:2181'` instead of `'zookeeper:2181'` and what ever is making the YAML puts quotes around that correctly

```
spouts:
- className: com.me.spouts.Spout
  constructorArgs: ['zookeeper:2181,zookeeper:2181', 'something else']
  id: some-java-spout
```

Its kind of annoying though

is this happening because of this commit
https://github.com/Parsely/streamparse/commit/32808a4e3cea08c91d641f1bb623693753c8e1ac
